# Generated by Django 4.1 on 2022-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Farmer', 'Farmer'), ('Researcher', 'Researcher'), ('Agro-scientist', 'Agro-scientist'), ('Drone Operator', 'Drone Operator'), ('KVK', 'KVK'), ('Warehouse', 'Warehouse'), ('Food Processor', 'Food Processor'), ('Distributer', 'Distributer'), ('Retailer', 'Retailer'), ('Others', 'Others')], max_length=80),
        ),
    ]
