# Generated by Django 4.1 on 2022-08-14 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_registration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone_operator',
            name='adhaar_number',
            field=models.CharField(default=12, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='adhaar_number',
            field=models.CharField(default=123412341234, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kvk',
            name='adhaar_number',
            field=models.CharField(default=1234, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='others',
            name='adhaar_number',
            field=models.CharField(default=123412341234, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research_agro',
            name='adhaar_number',
            field=models.CharField(default=123412341234, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='adhaar_number',
            field=models.CharField(default=123412341234, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,12}$')]),
            preserve_default=False,
        ),
    ]
