# Generated by Django 4.1 on 2022-08-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_login_managers_alter_login_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='login',
            managers=[
            ],
        ),
    ]
